######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 19:27:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH +=  . \
                ./src \
                ../global \
                ../../thirdparty/boost \
                ../../thirdparty/bamtools

# Input
SOURCES += a1.cpp
