######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 19:27:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH +=  . \
                ./src \
                ../global \
                ../../thirdparty/boost \
                ../../thirdparty/bamtools

macx{

QMAKE_CFLAGS_X86_64 += -mmacosx-version-min=10.7
QMAKE_CXXFLAGS_X86_64 = $$QMAKE_CFLAGS_X86_64

}

# Input
SOURCES += \
    a1.cpp
#    quicksort.cpp
#    inversions.cpp

