#!/bin/bash

rm *.txt*
rm *.log*

NAME_1_1="NaiveH3K4me3_l2_islands.txt"
NAME_2_1="EMH3K4me3_l2_islands.txt"
NAME_3_1="NaiveH2AZ_l2_islands.txt"
NAME_4_1="EMH2AZ_l2_islands.txt"

NAME_1_2="NaiveH3K4me3_b2_10_islands.txt"
NAME_2_2="EMH3K4me3_b2_10_islands.txt"
NAME_3_2="NaiveH2AZ_b2_10_islands.txt"
NAME_4_2="EMH2AZ_b2_10_islands.txt"

NAME_1_3="NaiveH3K4me3_b10_islands.txt"
NAME_2_3="EMH3K4me3_b10_islands.txt"
NAME_3_3="NaiveH2AZ_b10_islands.txt"
NAME_4_3="EMH2AZ_b10_islands.txt"


#NAME_1_1="NaiveH3K4me3_islands_2500_l2.txt"
#NAME_2_1="EMH3K4me3_islands_2500_l2.txt"
#NAME_3_1="NaiveH2AZ_islands_2500_l2.txt"
#NAME_4_1="EMH2AZ_islands_2500_l2.txt"

#NAME_1_2="NaiveH3K4me3_islands_2500_b2_10.txt"
#NAME_2_2="EMH3K4me3_islands_2500_b2_10.txt"
#NAME_3_2="NaiveH2AZ_islands_2500_b2_10.txt"
#NAME_4_2="EMH2AZ_islands_2500_b2_10.txt"

#NAME_1_3="NaiveH3K4me3_islands_2500_g10.txt"
#NAME_2_3="EMH3K4me3_islands_2500_g10.txt"
#NAME_3_3="NaiveH2AZ_islands_2500_g10.txt"
#NAME_4_3="EMH2AZ_islands_2500_g10.txt"



Q1_1="select chrom,chromStart,chromEnd from Naive_H3K4me3_Duplicate_236_8_sicer where chrom not like 'chrM' order by chrom,chromStart;"
Q1_2="select chrom,chromStart,chromEnd from EM_H3K4me3_Duplicate_241_5_sicer where chrom not like 'chrM' order by chrom,chromStart;"
Q1_3="select chrom,chromStart,chromEnd from Naive_H2AZ_208_5_sicer where chrom not like 'chrM' order by chrom,chromStart;"
Q1_4="select chrom,chromStart,chromEnd from EM_H2AZ_208_7_sicer where chrom not like 'chrM' order by chrom,chromStart;"

#Q3_UP="select chrom,txStart-1000,txStart from refGene WHERE name like 'NM\\\\_%' and strand='+'"
#Q3_MP="select chrom,txStart,txEnd from refGene WHERE name like 'NM\\\\_%' and strand='+'"
#Q3_DP="select chrom,txEnd,txEnd+1000 from refGene WHERE name like 'NM\\\\_%' and strand='+'"

#Q3_UN="select chrom,txEnd,txEnd+1000 from refGene WHERE name like 'NM\\\\_%' and strand='-'"
#Q3_MN="select chrom,txStart,txEnd from refGene WHERE name like 'NM\\\\_%' and strand='-'"
#Q3_DN="select chrom,txStart-1000,txStart from refGene WHERE name like 'NM\\\\_%' and strand='-'"

F_TABLE="expirements.TSS_TEMCD4Rna_seqPRE"

VALE_1="and value_1 <2"
VALE_2="and value_1 between 2 and 10"
VALE_3="and value_1 >10"


LIST="UP MP DP UN MN DN"
#LIST="MP MN"
INI="config/CCHMC/IsNormal.ini"

QUERYN="Q3_"


export OLD_NAME=""

for k in 1 2 3; do

eval VALE="\${VALE_${k}}"


COUNT="select distinct a.chrom,txStart,txEnd from refGene a,${F_TABLE} b WHERE name like 'NM\\\\_%' and name2=b.gene_id and sample_1='0h' and sample_2='40m' ${VALE} and a.strand=b.strand and a.chrom=b.chrom"

#Q3_MP="select distinct a.chrom,txStart-2500,txStart+2500 from refGene a,${F_TABLE} b WHERE a.strand='+' and name like 'NM\\\\_%' and name2=b.gene_id and sample_1='0h' and sample_2='40m' ${VALE} and a.strand=b.strand and a.chrom=b.chrom and txEnd-txStart>1000"
#Q3_MN="select distinct a.chrom,txStart-2500,txStart+2500 from refGene a,${F_TABLE} b WHERE a.strand='-' and name like 'NM\\\\_%' and name2=b.gene_id and sample_1='0h' and sample_2='40m' ${VALE} and a.strand=b.strand and a.chrom=b.chrom and txEnd-txStart>1000"

Q3_UP="select distinct a.chrom,txStart-100,txStart,txEnd,1 from refGene a,${F_TABLE} b WHERE a.strand='+' and name like 'NM\\\\_%' and name2=b.gene_id and sample_1='0h' and sample_2='40m' ${VALE} and a.strand=b.strand and a.chrom=b.chrom"
Q3_MP="select distinct a.chrom,txStart,txEnd from refGene a,${F_TABLE} b WHERE a.strand='+' and name like 'NM\\\\_%' and name2=b.gene_id and sample_1='0h' and sample_2='40m' ${VALE} and a.strand=b.strand and a.chrom=b.chrom"
Q3_DP="select distinct a.chrom,txEnd,txEnd+1000,txStart,1 from refGene a,${F_TABLE} b WHERE a.strand='+' and name like 'NM\\\\_%' and name2=b.gene_id and sample_1='0h' and sample_2='40m' ${VALE} and a.strand=b.strand and a.chrom=b.chrom"

Q3_UN="select distinct a.chrom,txEnd,txEnd+100,txStart,1 from refGene a,${F_TABLE} b WHERE a.strand='-' and name like 'NM\\\\_%' and name2=b.gene_id and sample_1='0h' and sample_2='40m' ${VALE} and a.strand=b.strand and a.chrom=b.chrom"
Q3_MN="select distinct a.chrom,txStart,txEnd from refGene a,${F_TABLE} b WHERE a.strand='-' and name like 'NM\\\\_%' and name2=b.gene_id and sample_1='0h' and sample_2='40m' ${VALE} and a.strand=b.strand and a.chrom=b.chrom"
Q3_DN="select distinct a.chrom,txStart-1000,txStart,txEnd,1 from refGene a,${F_TABLE} b WHERE a.strand='-' and name like 'NM\\\\_%' and name2=b.gene_id and sample_1='0h' and sample_2='40m' ${VALE} and a.strand=b.strand and a.chrom=b.chrom"

#------------------------------------------------------------------------------------------------------------------------------

for i in 1 2 3 4; do

eval Q1="\${Q1_${i}}"

eval NAME="\${NAME_${i}_${k}}"

echo "---------------------------------------------------------"
echo $NAME

for j in ${LIST}; do



eval Q3="\${${QUERYN}${j}}"
#Q3=${Q3}${FILTR}

echo ${j}
#echo "---------------------------------------------------------"

cat > ${INI} <<EOF
[General]
logFileName=./logfile.log

[SQL]
DRIVER=QMYSQL
DBNAME=hg19
HOST1=localhost
HOST=10.200.42.25
PORT=3306
USER=root
PASS="@ByteArray(AAAACnicsywqSU9JS89LKgMAFS0D/g==)"


[QUERIES]

Q1="${Q1}"
Q3="${Q3}"
COUNT="${COUNT}"

EOF

./IsNormal >/dev/null 2>&1

mv out_percentile_a_and_b.txt out_percentile_a_and_b_${j}.txt 
#echo|awk '{printf("N\t<SILENT\t>Expressed\tInducible\n");}' >${WORKD}/${BNAME}/${FTXT}
#paste ${WORKD}/${BNAME}/1/${FTXT} ${WORKD}/${BNAME}/2/${FTXT} "${WORKD}/${BNAME}/sum/${FTXT}" "${WORKD}/${BNAME}/Uniq/${FTXT}"| awk '{printf("%s\t%s\t%s\t%s\t%s\n",$1,$2,$4,$6,$8);}' >>${WORKD}/${BNAME}/${FTXT}
#paste ${WORKD}/${BNAME}/1/${FTXT} ${WORKD}/${BNAME}/2/${FTXT} "${WORKD}/${BNAME}/Uniq/${FTXT}" | awk '{printf("%s\t%s\t%s\t%s\n",$1,$2,$4,$6);}' >>${WORKD}/${BNAME}/${FTXT}


done

../../scripts/joiner_percentile.py >${NAME}

if [ -z "$OLD_NAME" ]; then 
cat $NAME >${NAME}_j
fi

if [ -n "$OLD_NAME" ]; then 
join -t $'\t' ${OLD_NAME}_j ${NAME} >${NAME}_j
fi


export OLD_NAME="${NAME}"

done

done