#!/bin/bash
#/****************************************************************************
#**
#** Copyright (C) 2011 Andrey Kartashov .
#** All rights reserved.
#** Contact: Andrey Kartashov (porter@porter.st)
#**
#** This file is part of the averagedensity module of the genome-tools.
#**
#** GNU Lesser General Public License Usage
#** This file may be used under the terms of the GNU Lesser General Public
#** License version 2.1 as published by the Free Software Foundation and
#** appearing in the file LICENSE.LGPL included in the packaging of this
#** file. Please review the following information to ensure the GNU Lesser
#** General Public License version 2.1 requirements will be met:
#** http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
#**
#** Other Usage
#** Alternatively, this file may be used in accordance with the terms and
#** conditions contained in a signed written agreement between you and Andrey Kartashov.
#**
#****************************************************************************/


#
#      DNAse does not need siteshifting 
#

export OUT_DIR="./res3"

mkdir ${OUT_DIR}

export FNAME_BASE="SRR089679"
/data/DEVEL/REPO/genome-tools/src/averagedensity/averagedensity -in="./batch.f" \
-out="${OUT_DIR}/${FNAME_BASE}.csv" -log="${OUT_DIR}/${FNAME_BASE}.log" -batch="./batch" \
-sam_twicechr="chrX chrY" -sam_ignorechr="chrM" -sam_siteshift=0 -avd_window=2000 -avd_smooth=50 -plot_ext="svg" -gnuplot="/usr/local/bin/gnuplot" &


#export FNAME_BASE="run0134_lane8_read1_index4=TE7_2hr_control"
#/data/DEVEL/REPO/genome-tools/src/averagedensity/averagedensity -in="./${FNAME_BASE}.fastq.bam" \
#-out="${OUT_DIR}/${FNAME_BASE}.txt" -log="${OUT_DIR}/${FNAME_BASE}.log" -batch="./batch" \
#-sam_twicechr="chrX chrY" -sam_ignorechr="chrM" -sam_siteshift=75 -avd_window=2000 -avd_smooth=50 -plot_ext="svg" -gnuplot="gnuplot" &

#export FNAME_BASE="run0134_lane8_read1_index5=TE7_2hr_IL13"
#/data/DEVEL/REPO/genome-tools/src/averagedensity/averagedensity -in="./${FNAME_BASE}.fastq.bam" \
#-out="${OUT_DIR}/${FNAME_BASE}.txt" -log="${OUT_DIR}/${FNAME_BASE}.log" -batch="./batch" \
#-sam_twicechr="chrX chrY" -sam_ignorechr="chrM" -sam_siteshift=75 -avd_window=2000 -avd_smooth=50 -plot_ext="svg" -gnuplot="gnuplot" &


#export FNAME_BASE="run0140_lane7_read1_index6=TE7_6hr_control"
#/data/DEVEL/REPO/genome-tools/src/averagedensity/averagedensity -in="./${FNAME_BASE}.fastq.bam" \
#-out="${OUT_DIR}/${FNAME_BASE}.txt" -log="${OUT_DIR}/${FNAME_BASE}.log" -batch="./batch" \
#-sam_twicechr="chrX chrY" -sam_ignorechr="chrM" -sam_siteshift=75 -avd_window=2000 -avd_smooth=50 -plot_ext="svg" -gnuplot="gnuplot" &

#export FNAME_BASE="run0140_lane7_read1_index12=TE7_6hr_IL13"
#/data/DEVEL/REPO/genome-tools/src/averagedensity/averagedensity -in="./${FNAME_BASE}.fastq.bam" \
#-out="${OUT_DIR}/${FNAME_BASE}.txt" -log="${OUT_DIR}/${FNAME_BASE}.log" -batch="./batch" \
#-sam_twicechr="chrX chrY" -sam_ignorechr="chrM" -sam_siteshift=75 -avd_window=2000 -avd_smooth=50 -plot_ext="svg" -gnuplot="gnuplot" &


