#!/bin/bash

WORKD="/mnt/sf_G_DRIVE/FASTQ-DATA/results"

CM_LINE="CM-H2AZ-208-6.bam CM-H3K4me1-208-3.bam CM-H3K4me1-Duplicate-234-7.bam CM-H3K4me1-Duplicate-319-5.bam CM-H3K4me3-47-1.bam CM-H3K4me3-75-3.bam CM-H3K4me3-Duplicate-241-4.bam"
EM_LINE="EM-H2AZ-208-7.bam EM-H3K4me1-208-4.bam EM-H3K4me1-234-8.bam EM-H3K4me1-Duplicate-319-6.bam EM-H3K4me3-48-1.bam EM-H3K4me3-75-5.bam EM-H3K4me3-Duplicate-241-5.bam"
NAIVE_L="Naive-H2AZ-208-5.bam Naive-H3K4me1-205-7.bam Naive-H3K4me1-208-2.bam Naive-H3K4me1-Duplicate-234-6.bam Naive-H3K4me1-Duplicate-319-4.bam Naive-H3K4me3-47-3.bam Naive-H3K4me3-75-1.bam Naive-H3K4me3-Duplicate-236-8.bam"
NAIVE_L="Naive-H2AZ-208-5.bam CM-H2AZ-208-6.bam EM-H2AZ-208-7.bam CM-H3K4me3-Duplicate-241-4.bam EM-H3K4me3-Duplicate-241-5.bam Naive-H3K4me3-Duplicate-236-8.bam"

SENSE_SITE_QUERY_0="SELECT distinct chrom,l_start FROM TSS_TEMCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and strand='+' and sample_1='0h' and value_1<=2.0 and value_2>=2.0 and significant='yes' and TSS_group_id not in (SELECT distinct TSS_group_id FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and sample_1='0h' and value_1<=2.0 and value_2>=2.0 and significant='yes') order by chrom,l_start"
NSENSE_SITE_QUERY_0="SELECT distinct chrom,l_end FROM TSS_TEMCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and strand='-' and sample_1='0h' and value_1<=2.0 and value_2>=2.0 and significant='yes' and TSS_group_id not in (SELECT distinct TSS_group_id FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and sample_1='0h' and value_1<=2.0 and value_2>=2.0 and significant='yes') order by chrom,l_end"
#SENSE_SITE_QUERY_0="SELECT distinct chrom,l_start FROM TSS_TCMCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and strand='+' and sample_1='0h' and value_1<=2.0 and value_2>=2.0 and significant='yes'"
#  and TSS_group_id not in (SELECT distinct TSS_group_id FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and sample_1='0h' and value_1<=2.0  and significant='yes') order by chrom,l_start"
#NSENSE_SITE_QUERY_0="SELECT distinct chrom,l_end FROM TSS_TCMCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and strand='-' and sample_1='0h' and value_1<=2.0 and value_2>=2.0 and significant='yes'" 
# and TSS_group_id not in (SELECT distinct TSS_group_id FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and sample_1='0h' and value_1<=2.0  and significant='yes') order by chrom,l_end"

SENSE_SITE_QUERY_1="SELECT distinct chrom,l_start FROM TSS_TCMCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='+' and length>200 and sample_1='0h' and value_1<=2.0 and value_2<=2.0 order by chrom,l_start ;"
NSENSE_SITE_QUERY_1="SELECT distinct chrom,l_end FROM TSS_TCMCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='-' and length>200 and sample_1='0h' and value_1<=2.0 and value_2<=2.0 order by chrom,l_end ;"

SENSE_SITE_QUERY_2="SELECT distinct chrom,l_start FROM TSS_TCMCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='+' and length>200 and sample_1='0h' and value_1>10.0 order by chrom,l_start ;"
NSENSE_SITE_QUERY_2="SELECT distinct chrom,l_end FROM TSS_TCMCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='-' and length>200 and sample_1='0h' and value_1>10.0 order by chrom,l_end ;"

SENSE_SITE_QUERY_3="SELECT distinct chrom,l_start FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='+' and length>200 and significant='yes' and sample_1='0h' and value_1<=2.0 order by chrom,l_start ;"
NSENSE_SITE_QUERY_3="SELECT distinct chrom,l_end FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='-' and length>200 and significant='yes' and sample_1='0h' and value_1<=2.0 order by chrom,l_end ;"


#RUNS=("Uniq" "1" 2" "sum")
RUNS=("Uniq")

INI="config/CCHMC/averagedensity.ini"

QUERYN="SENSE_SITE_QUERY_"

QCOUNT=0

for j in ${NAIVE_L}; do

BNAME=`basename ${j} .bam`
FTXT="${BNAME}.txt"

ln -f -s ${WORKD}/${j} ./${j}


for i in 0; do


OUTDIR="${WORKD}/${BNAME}/${RUNS[$i]}"

if [ -d "$OUTDIR" ] ; then
 echo $OUTDIR
 continue 
fi

#echo ${RUNS[$i]}


eval SQUERY="\${${QUERYN}${i}}"
eval NQUERY="\${N${QUERYN}${i}}"


FBAM="${BNAME}.bam"

cat > ${INI} <<EOF
[General]
logFileName=./logfile.log
HeaderString="track type=bedGraph name=%1"
graphWindow=200
siteShift=75
graphFileName=./output.bedgraph
outFileName=${FTXT}
inFileName=${FBAM}
AvgTagWindow=4000

[SQL]
DRIVER=QMYSQL
DBNAME=expirements
HOST=bmigbdb1.chmcres.cchmc.org
PORT=3306
USER=root
PASS="@ByteArray(AAAACnicsywqSU9JS89LKgMAFS0D/g==)"
HOST1=localhost

[QUERIES]
SENSE_SITE_QUERY="${SQUERY}"
NSENSE_SITE_QUERY="${NQUERY}"

[QUERIES2]
SENSE_SITE_QUERY_1="SELECT distinct chrom,l_start FROM TSS_TEMCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and strand='+' and sample_1='0h' and value_1<=2.0  and significant='yes'  and TSS_group_id not in (SELECT distinct TSS_group_id FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and sample_1='0h' and value_1<=2.0  and significant='yes') order by chrom,l_start"
NSENSE_SITE_QUERY_1="SELECT distinct chrom,l_end FROM TSS_TEMCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and strand='-' and sample_1='0h' and value_1<=2.0  and significant='yes'  and TSS_group_id not in (SELECT distinct TSS_group_id FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and sample_1='0h' and value_1<=2.0  and significant='yes') order by chrom,l_end"
SENSE_SITE_QUERY_3="SELECT distinct chrom,l_start FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='+' and length>200 and significant='yes' and sample_1='0h' and value_1<=2.0 order by chrom,l_start ;"
NSENSE_SITE_QUERY_3="SELECT distinct chrom,l_end FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='-' and length>200 and significant='yes' and sample_1='0h' and value_1<=2.0 order by chrom,l_end ;"
SENSE_SITE_QUERY_2="SELECT distinct chrom,l_start FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='+' and length>200 and sample_1='0h' and value_1<=2.0 order by chrom,l_start ;"
NSENSE_SITE_QUERY_2="SELECT distinct chrom,l_end FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='-' and length>200 and sample_1='0h' and value_1<=2.0 order by chrom,l_end ;"

[QUERIESSAVE]
SENSE_SITE_QUERY_1="SELECT distinct chrom,txStart FROM refGene where chrom not like '%random%' and strand='+' order by chrom,txStart ;"
NSENSE_SITE_QUERY_1="SELECT distinct chrom,txEnd FROM refGene where chrom not like '%random%' and strand='-' order by chrom,txEnd ;"
SENSE_SITE_QUERY_3="SELECT distinct chrom,l_start FROM TSS_TCMCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='+' order by chrom,l_start ;"
NSENSE_SITE_QUERY_3="SELECT distinct chrom,l_end FROM TSS_TCMCD4Rna_seqPRE where chrom not like '%\\\\_%' and strand='-' order by chrom,l_end ;"
SENSE_SITE_QUERY_5="SELECT distinct chrom,l_start FROM TSS_TEMCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and strand='+' and sample_1='0h' and value_1<=2.0  and significant='yes' and TSS_group_id not in (SELECT distinct TSS_group_id FROM TSS_TCMCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and sample_1='0h' and value_1<=2.0  and significant='yes') and TSS_group_id not in (SELECT distinct TSS_group_id FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and sample_1='0h' and value_1<=2.0  and significant='yes') order by chrom,l_start"
NSENSE_SITE_QUERY_5="SELECT distinct chrom,l_end FROM TSS_TEMCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and strand='-' and sample_1='0h' and value_1<=2.0  and significant='yes' and TSS_group_id not in (SELECT distinct TSS_group_id FROM TSS_TCMCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and sample_1='0h' and value_1<=2.0  and significant='yes') and TSS_group_id not in (SELECT distinct TSS_group_id FROM TSS_NaiveCD4Rna_seqPRE where chrom not like '%\\\\_%' and length>200 and sample_1='0h' and value_1<=2.0  and significant='yes') order by chrom,l_end"

[SAM]
RMODE=rb

[PLOT]
width=1920
height=1080
maxX=
title=
xname="Position relative to TSS, kb"
yname=Normalized tag density
fileName=${BNAME}
maxY=2.0e-08

EOF


##do averagedensity
##move some files


echo "start AVD ${BNAME}, ${RUNS[$i]}"

#exit
./averagedensity

mkdirhier ${OUTDIR}

mv ./${FTXT} ${OUTDIR}
mv "./${BNAME}.png" ${OUTDIR}

echo "complite AVD ${BNAME} ,${RUNS[$i]}"

done


#echo|awk '{printf("N\t<SILENT\t>Expressed\tInducible\n");}' >${WORKD}/${BNAME}/${FTXT}
#paste ${WORKD}/${BNAME}/1/${FTXT} ${WORKD}/${BNAME}/2/${FTXT} "${WORKD}/${BNAME}/sum/${FTXT}" "${WORKD}/${BNAME}/Uniq/${FTXT}"| awk '{printf("%s\t%s\t%s\t%s\t%s\n",$1,$2,$4,$6,$8);}' >>${WORKD}/${BNAME}/${FTXT}
#paste ${WORKD}/${BNAME}/1/${FTXT} ${WORKD}/${BNAME}/2/${FTXT} "${WORKD}/${BNAME}/Uniq/${FTXT}" | awk '{printf("%s\t%s\t%s\t%s\n",$1,$2,$4,$6);}' >>${WORKD}/${BNAME}/${FTXT}


done

