OTHER_FILES += \
    index.html \
    app.js \
    app.css \
    app/controller/WorkersEdit.js \
    app/controller/ProtocolEdit.js \
    app/controller/GenomeEdit.js \
    app/controller/ExperimentTypeEdit.js \
    app/controller/ExperimentsWindow.js \
    app/controller/EMSMenu.js \
    images/windows.png \
    images/users3.png \
    images/users3_preferences.png \
    images/users3_edit.png \
    images/users3_delete.png \
    images/users3_add.png \
    images/user.png \
    images/user_time.png \
    images/user_refresh.png \
    images/user_preferences.png \
    images/user_new.png \
    images/user_monitor.png \
    images/user_information.png \
    images/user_add.png \
    images/undo.png \
    images/text_underlined.png \
    images/text_italics.png \
    images/text_bold.png \
    images/text_align_right.png \
    images/text_align_left.png \
    images/text_align_justified.png \
    images/table2.png \
    images/table2_view.png \
    images/table2_selection_all.png \
    images/table2_ok.png \
    images/table2_check.png \
    images/table2_add.png \
    images/table_row_add.png \
    images/table_refresh.png \
    images/table_ok.png \
    images/spellcheck.png \
    images/refresh.png \
    images/recycle.png \
    images/printer.png \
    images/potion_blue.png \
    images/pill2_blue.png \
    images/pill_blue.png \
    images/page_attach.png \
    images/notebook3.png \
    images/notebook2.png \
    images/notebook.png \
    images/notebook_preferences.png \
    images/notebook_edit.png \
    images/notebook_delete.png \
    images/notebook_add.png \
    images/nav_refresh_blue.png \
    images/magnet.png \
    images/magazine_folder.png \
    images/magazine_folder_empty.png \
    images/layout-icon.gif \
    images/layout-browser-hd-bg.gif \
    images/information2.png \
    images/hospital.png \
    images/gear.png \
    images/garbage.png \
    images/form_blue.png \
    images/form_blue_edit.png \
    images/form_blue_delete.png \
    images/form_blue_add.png \
    images/folder3.png \
    images/folder2.png \
    images/folder.png \
    images/folder_document.png \
    images/flower_blue.png \
    images/email_go.png \
    images/disk.png \
    images/cube_molecule.png \
    images/clock.png \
    images/checks.png \
    images/checkbox.png \
    images/check.png \
    images/chart_radar.png \
    images/chart_pie2.png \
    images/chart_pie.png \
    images/chart_line.png \
    images/chart_gantt.png \
    images/chart_dot.png \
    images/chart_donut.png \
    images/chart_column.png \
    images/chart_bubble.png \
    images/chart_bar.png \
    images/chart_area.png \
    images/bottle.png \
    images/bottle_of_pills.png \
    images/battery_red_10.png \
    images/battery_green_67.png \
    images/baby.png \
    images/atom.png \
    images/athlete.png \
    images/astrologer.png \
    images/army_knife.png \
    images/apple.png \
    images/ambulance.png \
    app/model/Worker.js \
    app/model/Protocol.js \
    app/model/LabData.js \
    app/model/Genome.js \
    app/model/Fragmentation.js \
    app/model/ExperimentType.js \
    app/model/Crosslinking.js \
    app/model/Antibodies.js \
    app/store/Worker.js \
    app/store/Protocol.js \
    app/store/LabData.js \
    app/store/Genome.js \
    app/store/Fragmentation.js \
    app/store/ExperimentType.js \
    app/store/Crosslinking.js \
    app/store/Antibodies.js \
    app/view/charts/Fence.js \
    app/view/ExperimentsWindow/Main.js \
    app/view/ExperimentsWindow/Grid.js \
    app/view/LabDataEdit/LabDataEdit.js \
    app/view/user/List.js \
    app/view/user/Edit.js \
    app/view/WorkersEdit.js \
    app/view/EMSMenu.js \
    ux/IFrame.js \
    app/view/Antibodies/List.js \
    app/view/Antibodies/Edit.js \
    app/controller/AntibodiesEdit.js \
    app/view/Antibodies/Antibodies.js \
    app/view/ExperimentType/List.js \
    app/view/ExperimentType/ExperimentType.js \
    app/view/Fragmentation/List.js \
    app/view/Fragmentation/Fragmentation.js \
    app/controller/FragmentationEdit.js \
    index.php \
    login.php \
    common.php \
    authenticate.php \
    app/view/Crosslink/List.js \
    app/view/Crosslink/Crosslink.js \
    app/controller/CrosslinkEdit.js \
    app/view/Genome/List.js \
    app/view/Genome/Genome.js \
    ../sql/EMS.sql
