######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 19 14:59:16 2011
######################################################################

TEMPLATE = app
TARGET = sam2bedgraph

CONFIG   += console warn_on release
QT       -= gui
QT       += sql


OBJECTS_DIR = build
UI_DIR      = build
MOC_DIR     = build
RCC_DIR     = build

DEFINES     += _APPNAME=\\\"$$TARGET\\\" \
               D_USE_SAM


HEADERS     += ../global/SamReader.hpp \
#               ../global/FileWriter.hpp \
#               ../global/PostHandler.hpp \
#               ../global/BEDHandler.hpp \
               ../global/Reads.hpp \
               src/sam2bedgraph.hpp 
               
#../global/SamReader.cpp \               
SOURCES     +=  \
#               ../global/FileWriter.cpp \
#               ../global/PostHandler.cpp \
#               ../global/BEDHandler.cpp \
               ../global/Reads.cpp \
               src/main.cpp \
               src/sam2bedgraph.cpp 

INCLUDEPATH += . \
               ./src \
               ../global \
               ../../thirdparty/samtools-0.1.18 \
               ../../thirdparty/boost
#               ../../thirdparty/mathgl-1.11.2/include

DEPENDPATH  += .


LIBS        += ../../thirdparty/samtools-0.1.18/libbam.a \
               -lgsl -lpng -lgslcblas -lm -lz
#               ../../thirdparty/mathgl-1.11.2/mgl/.libs/libmgl.a \

QMAKE_CXXFLAGS += -Werror

make_clean.commands = $(MAKE) clean

lib_samtools.commands = cd ../../thirdparty/samtools-0.1.18/; $(MAKE) -j 8

QMAKE_EXTRA_TARGETS = lib_samtools make_clean
PRE_TARGETDEPS      = lib_samtools make_clean

QMAKE_CLEAN += $$TARGET logfile.log *~ ../global/*~

